baseurl = "https://johntheo.github.io"
canonifyurls = true
defaultContentLanguage = "pt-br"
disqusShortname = "johntheo-github"
googleAnalytics = "UA-94125077-1"
languageCode = "pt-br"
paginate = 7
theme = "tranquilpeak"
title = "johntheology"
[author]
bio = "Misturando arte com tecnologia para dar novas cores ao cotidiano"
gravatarEmail = "john.theo.souza@gmail.com"
job = "Engenheiro de Computação | Músico | Pesquisador Machine Learning"
location = "Brasil"
name = "John Theo"
picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
twitter = "john_theo"
[[menu.links]]
identifier = "twitter"
name = "Twitter"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
url = "https://twitter.com/john_theo"
weight = 1
[[menu.links]]
identifier = "github"
name = "GitHub"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
url = "https://github.com/johntheo"
weight = 2
[[menu.main]]
identifier = "about"
name = "Sobre"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
url = "/#about"
weight = 0
[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/tags"
weight = 2
[[menu.main]]
identifier = "categories"
name = "Categorias"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
url = "/categories"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
url = "/"
weight = 1
[[menu.misc]]
identifier = "rss"
name = "RSS"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
url = "/index.xml"
weight = 0
[params]
autothumbnailimage = true
clearreading = true
coverimage = "ep_naturalblack.png"
dateformat = "02-Jun-2017"
description = "Um blog de artesanado computacional"
favicon = "images/favicon.png"
hierarchicalcategories = true
imagegallery = true
sidebarbehavior = 6
thumbnailimage = true
thumbnailimageposition = "bottom"
[params.header.rightlink]
class = ""
icon = ""
url = "/#about"
[permalinks]
post = "/:year/:month/:slug/"
[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
